import type { Schema } from "./types";

export const mockSchemas: Schema[] = [
  {
    name: "users",
    graphql: { enabled: true },
    enums: [{ name: "platform_role", values: ["ADMIN", "SUPPORT", "USER"] }],
    tables: [
      {
        name: "user_account",
        graphql: { queries: true, mutations: { create: false, update: false, delete: false } },
        history: {
          enabled: false,
          mode: "snapshot",
          excludeColumns: ["updated_at"],
          logInsert: false,
          logUpdate: false,
          logDelete: false,
        },
        files: [
          {
            column_name: "avatar",
            enabled: true,
            provider: "local",
            maxSizeMb: 10,
            allowedMimeTypes: ["image/png", "image/jpeg", "image/webp"],
          },
        ],
        columns: [
          { name: "id", type: "UUID", nullable: false, default: "uuidv7()" },
          { name: "login", type: "VARCHAR(150)", nullable: false },
          {
            name: "platform_role",
            type: "users.platform_role",
            nullable: false,
            default: "'USER'",
          },
          { name: "is_active", type: "BOOLEAN", nullable: false, default: "true" },
          { name: "created_at", type: "TIMESTAMPTZ", nullable: false, default: "now()" },
          { name: "updated_at", type: "TIMESTAMPTZ", nullable: false, default: "now()" },
        ],
        constraints: [
          { type: "primary", name: "user_account_pkey", columns: ["id"] },
          { type: "unique", name: "user_account_login_unique", columns: ["login"] },
        ],
        indexes: [{ name: "idx_user_active", columns: ["is_active"], where: "is_active = TRUE" }],
      },
      {
        name: "person_data",
        graphql: { queries: true, mutations: { create: true, update: true, delete: true } },
        history: {
          enabled: true,
          mode: "diff",
          excludeColumns: ["updated_at"],
          logInsert: true,
          logUpdate: true,
          logDelete: true,
        },
        columns: [
          { name: "user_id", type: "UUID", nullable: false },
          { name: "email", type: "VARCHAR(255)", nullable: false },
          { name: "email_verified", type: "BOOLEAN", nullable: false, default: "false" },
          { name: "phone", type: "VARCHAR(30)", nullable: false },
          { name: "home_phone", type: "VARCHAR(30)", nullable: true },
          { name: "first_name", type: "VARCHAR(100)", nullable: true },
          { name: "last_name", type: "VARCHAR(100)", nullable: true },
          { name: "created_at", type: "TIMESTAMPTZ", nullable: false, default: "now()" },
          { name: "updated_at", type: "TIMESTAMPTZ", nullable: false, default: "now()" },
        ],
        constraints: [
          { type: "primary", name: "person_data_pkey", columns: ["user_id"] },
          {
            type: "foreign",
            name: "person_data_user_fk",
            columns: ["user_id"],
            references: { schema: "users", table: "user_account", columns: ["id"] },
            onDelete: "CASCADE",
          },
          { type: "unique", name: "person_data_email_unique", columns: ["email"] },
          { type: "unique", name: "person_data_phone_unique", columns: ["phone"] },
        ],
        indexes: [
          { name: "idx_person_data_user_id", columns: ["user_id"] },
          { name: "idx_person_data_email", columns: ["email"] },
          { name: "idx_person_data_phone", columns: ["phone"] },
          { name: "idx_person_data_first_name", columns: ["first_name"] },
          { name: "idx_person_data_last_name", columns: ["last_name"] },
        ],
      },
      {
        name: "web_auth",
        graphql: { queries: false, mutations: { create: false, update: false, delete: false } },
        history: {
          enabled: false,
          mode: "diff",
          excludeColumns: [],
          logInsert: false,
          logUpdate: false,
          logDelete: false,
        },
        columns: [
          { name: "user_id", type: "UUID", nullable: false },
          { name: "password_hash", type: "TEXT", nullable: false },
          { name: "password_changed_at", type: "TIMESTAMPTZ", nullable: true },
          { name: "created_at", type: "TIMESTAMPTZ", nullable: false, default: "now()" },
          { name: "updated_at", type: "TIMESTAMPTZ", nullable: false, default: "now()" },
        ],
        constraints: [
          { type: "primary", name: "web_auth_pkey", columns: ["user_id"] },
          {
            type: "foreign",
            name: "web_auth_user_fk",
            columns: ["user_id"],
            references: { schema: "users", table: "user_account", columns: ["id"] },
            onDelete: "CASCADE",
          },
        ],
        indexes: [{ name: "idx_web_auth_user_id", columns: ["user_id"] }],
      },
      {
        name: "google_auth",
        graphql: { queries: false, mutations: { create: false, update: false, delete: false } },
        history: {
          enabled: false,
          mode: "diff",
          excludeColumns: [],
          logInsert: false,
          logUpdate: false,
          logDelete: false,
        },
        columns: [
          { name: "user_id", type: "UUID", nullable: false },
          { name: "google_user_id", type: "VARCHAR(255)", nullable: false },
          { name: "connected_at", type: "TIMESTAMPTZ", nullable: false, default: "now()" },
          { name: "created_at", type: "TIMESTAMPTZ", nullable: false, default: "now()" },
          { name: "updated_at", type: "TIMESTAMPTZ", nullable: false, default: "now()" },
        ],
        constraints: [
          { type: "primary", name: "google_auth_pkey", columns: ["user_id"] },
          {
            type: "foreign",
            name: "google_auth_user_fk",
            columns: ["user_id"],
            references: { schema: "users", table: "user_account", columns: ["id"] },
            onDelete: "CASCADE",
          },
          { type: "unique", name: "google_auth_google_user_id_key", columns: ["google_user_id"] },
        ],
        indexes: [{ name: "idx_google_auth_user_id", columns: ["user_id"] }],
      },
    ],
    views: [
      {
        name: "test_view",
        code: "select ua.id, ua.login, ua.is_active, pd.email, pd.email_verified, pd.phone, pd.home_phone, pd.first_name, pd.last_name, pd.created_at, pd.updated_at from users.user_account ua left join users.person_data pd on pd.user_id = ua.id;",
        columns: [
          { name: "id", type: "uuid", nullable: true },
          { name: "login", type: "character varying", nullable: true },
          { name: "is_active", type: "boolean", nullable: true },
          { name: "email", type: "character varying", nullable: true },
          { name: "email_verified", type: "boolean", nullable: true },
          { name: "phone", type: "character varying", nullable: true },
          { name: "home_phone", type: "character varying", nullable: true },
          { name: "first_name", type: "character varying", nullable: true },
          { name: "last_name", type: "character varying", nullable: true },
          { name: "created_at", type: "timestamp with time zone", nullable: true },
          { name: "updated_at", type: "timestamp with time zone", nullable: true },
        ],
        graphql: { queries: true },
      },
    ],
    functions: [
      {
        name: "set_updated_at",
        definition:
          "CREATE OR REPLACE FUNCTION users.set_updated_at() RETURNS trigger AS $$ BEGIN NEW.updated_at := now(); RETURN NEW; END; $$ LANGUAGE plpgsql;",
      },
    ],
    triggers: [
      {
        name: "trg_users_updated_at",
        table: "user_account",
        timing: "BEFORE",
        event: "UPDATE",
        functionName: "set_updated_at",
      },
      {
        name: "trg_person_data_updated_at",
        table: "person_data",
        timing: "BEFORE",
        event: "UPDATE",
        functionName: "set_updated_at",
      },
      {
        name: "trg_web_auth_updated_at",
        table: "web_auth",
        timing: "BEFORE",
        event: "UPDATE",
        functionName: "set_updated_at",
      },
      {
        name: "trg_google_auth_updated_at",
        table: "web_auth",
        timing: "BEFORE",
        event: "UPDATE",
        functionName: "set_updated_at",
      },
    ],
  },
  {
    name: "organisations",
    graphql: { enabled: true },
    enums: [],
    tables: [
      {
        name: "organisation",
        graphql: { queries: false, mutations: { create: false, update: false, delete: false } },
        history: {
          enabled: true,
          mode: "snapshot",
          excludeColumns: [],
          logInsert: true,
          logUpdate: true,
          logDelete: true,
        },
        columns: [
          { name: "id", type: "BIGSERIAL", nullable: false },
          { name: "name", type: "VARCHAR(120)", nullable: false },
          { name: "full_name", type: "TEXT", nullable: true },
          { name: "ipn_edrpu", type: "INTEGER", nullable: true },
          { name: "owner_id", type: "UUID", nullable: false },
        ],
        constraints: [
          { type: "primary", name: "organisation_pkey", columns: ["id"] },
          { type: "unique", name: "organisation_name_unique", columns: ["name"] },
          {
            type: "check",
            name: "organisation_name_format_check",
            expression: "name ~ '^[a-zA-Z_]+$'",
          },
          {
            type: "foreign",
            name: "organisation_owner_fk",
            columns: ["owner_id"],
            references: { schema: "users", table: "user_account", columns: ["id"] },
            onDelete: "RESTRICT",
          },
        ],
        indexes: [{ name: "idx_organisation_owner", columns: ["owner_id"] }],
      },
    ],
    views: [],
    functions: [],
    triggers: [],
  },
];
